from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

RAW_LOG_PATH = BASE_DIR / "data/raw/auth_all_real.log"
LABELS_PATH = BASE_DIR / "data/labels.csv"

NIGHT_ACTIVITY_START = 22
NIGHT_ACTIVITY_END = 5

FAILED_LOGIN_WINDOW_SECONDS = 300
FAILED_LOGIN_THRESHOLD = 5

ISOLATION_FOREST_CONTAMINATION = 0.20
LOCAL_OUTLIER_FACTOR_CONTAMINATION = 0.20
RANDOM_STATE = 42
